//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int ID { get; set; }
        public int PatientID { get; set; }
        public string Cellphone { get; set; }
        public string Cellphone2 { get; set; }
        public string Email { get; set; }
        public bool Active { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
