# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('id_number', models.IntegerField()),
                ('cell_phone', models.IntegerField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Kin',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(max_length=10)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('weight', models.IntegerField(max_length=3)),
                ('height', models.IntegerField(max_length=3)),
                ('county', models.CharField(max_length=10)),
                ('sub_county', models.CharField(max_length=10)),
                ('ward', models.CharField(max_length=10)),
                ('village', models.CharField(max_length=10)),
                ('cell_phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('alternate_cell', models.IntegerField(max_length=10)),
                ('enroll_date', models.DateField(auto_now_add=True)),
                ('enroll_number', models.IntegerField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.AddField(
            model_name='kin',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Patient'),
        ),
    ]
