# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kin',
            name='cell_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alternate_cell',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cell_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='county',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='enroll_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sub_county',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='village',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ward',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
