# Generated by Django 2.0.3 on 2018-06-18 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('T', 'Telephone'), ('E', 'Email')], max_length=15)),
                ('value', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nok_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('dob', models.DateField()),
                ('county', models.CharField(choices=[('N', 'Nairobi County'), ('M', 'Mombasa County'), ('K', 'Kilifi County'), ('NY', 'Nyeri County'), ('KS', 'Kisumu County')], max_length=5)),
                ('sub_county', models.CharField(max_length=250, null=True)),
                ('ward', models.CharField(max_length=250, null=True)),
                ('village', models.CharField(max_length=250, null=True)),
                ('is_patient', models.BooleanField()),
                ('enrollment_date', models.DateField(null=True)),
                ('enrollment_number', models.CharField(max_length=250, null=True)),
                ('is_nok', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='nok_details',
            name='nok_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nok_details_record_indexed', to='records.Patient'),
        ),
        migrations.AddField(
            model_name='nok_details',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nok_details_record_owner', to='records.Patient'),
        ),
        migrations.AddField(
            model_name='contact',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.Patient'),
        ),
    ]
