# Generated by Django 2.0.3 on 2018-06-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20180619_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nok',
            field=models.ManyToManyField(to='records.Patient'),
        ),
    ]
