# Generated by Django 2.0.3 on 2018-06-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20180619_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('A', 'Add Record'), ('E', 'Edit Record'), ('D', 'Delete Record')], max_length=1)),
                ('narration', models.TextField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nok_details',
            name='nok_to',
        ),
        migrations.RemoveField(
            model_name='nok_details',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Nok_details',
        ),
    ]
