# Generated by Django 2.0.3 on 2018-06-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20180620_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
