# Generated by Django 2.0.3 on 2018-06-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20180620_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
