# Generated by Django 2.0.3 on 2018-06-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20180628_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('A', 'Add Record'), ('E', 'Edit Record'), ('D', 'Delete Record'), ('S', 'Search Operation'), ('P', 'API Access')], max_length=1),
        ),
    ]
